"""Use-Cases der monitoring-Domaene und ihre Application-Exceptions."""

from application.monitoring.behavior_profile import (
    BehaviorProfile,
    DayBandSlot,
    DaySlot,
    ProfileSample,
    analyze_behavior,
    build_day_band,
    build_week_heatmap,
    count_recorded_days,
)
from application.monitoring.errors import (
    LoggingTaskConflict,
    LoggingTaskNotFound,
    MonitoringApplicationError,
)
from application.monitoring.series_analysis import (
    EnrichedRttSample,
    HeatmapSlot,
    LatencySlot,
    OutageInterval,
    RankEntry,
    SeriesAnalysis,
    SeriesMetrics,
    analyze_series,
    build_heatmap,
    build_latency_slots,
    build_outages,
    build_ranking,
    compute_metrics,
)
from application.monitoring.use_cases import (
    AddMonitorTarget,
    CheckLogVolume,
    CreateLoggingTask,
    DeleteLoggingTask,
    DeleteMonitorTarget,
    EnforceLoggingRetention,
    GetAllSlaStats,
    GetLoggingTaskDetail,
    GetLoggingTaskEvents,
    GetLoggingTaskRtt,
    GetLoggingTaskSla,
    GetMonitorEvents,
    GetRttHistory,
    GetSchedules,
    GetSlaStats,
    ListLoggingTasks,
    LoggingRetentionResult,
    LogVolumeResult,
    ManageSchedules,
    PauseLoggingTask,
    RecordScheduleResult,
    RecordScheduleRun,
    ResumeActiveLoggingTasks,
    ResumeLoggingTask,
    ResumeResult,
    RunLoggingRetention,
    RunMonitor,
    StartLoggingTask,
    StopLoggingTask,
    UpdateSchedule,
)

# Re-Export der Domaenen-Exception, damit der api-Rand sie fangen kann, OHNE
# ``domain`` direkt zu importieren (import-linter: api -> nur application). Der
# Lifecycle-Use-Case reicht ``InvalidTaskTransition`` aus der Domaene unveraendert
# durch; der Router mappt sie auf 409 -- darum braucht er den Namen aus dieser
# Schicht (Muster: die application-Schicht ist die einzige, die der api-Ring kennt).
from domain.monitoring import InvalidTaskTransition

__all__ = [
    "AddMonitorTarget",
    "BehaviorProfile",
    "CheckLogVolume",
    "CreateLoggingTask",
    "DayBandSlot",
    "DaySlot",
    "DeleteLoggingTask",
    "DeleteMonitorTarget",
    "EnforceLoggingRetention",
    "EnrichedRttSample",
    "GetAllSlaStats",
    "GetLoggingTaskDetail",
    "GetLoggingTaskEvents",
    "GetLoggingTaskRtt",
    "GetLoggingTaskSla",
    "GetMonitorEvents",
    "GetRttHistory",
    "GetSchedules",
    "GetSlaStats",
    "HeatmapSlot",
    "InvalidTaskTransition",
    "LatencySlot",
    "ListLoggingTasks",
    "LogVolumeResult",
    "LoggingRetentionResult",
    "LoggingTaskConflict",
    "LoggingTaskNotFound",
    "ManageSchedules",
    "MonitoringApplicationError",
    "OutageInterval",
    "PauseLoggingTask",
    "ProfileSample",
    "RankEntry",
    "RecordScheduleResult",
    "RecordScheduleRun",
    "ResumeActiveLoggingTasks",
    "ResumeLoggingTask",
    "ResumeResult",
    "RunLoggingRetention",
    "RunMonitor",
    "SeriesAnalysis",
    "SeriesMetrics",
    "StartLoggingTask",
    "StopLoggingTask",
    "UpdateSchedule",
    "analyze_behavior",
    "analyze_series",
    "build_day_band",
    "build_heatmap",
    "build_latency_slots",
    "build_outages",
    "build_ranking",
    "build_week_heatmap",
    "compute_metrics",
    "count_recorded_days",
]
